### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by aptrn** [AndrewBelt/HelloDAW#3]
Hello Andrew,

I'm loving this project so far, it makes much more easy and straight-forward compiling your own VSTs than struggling with VS, IDEs etc, but how about graphics? Are you planning to add a widget based gui editing like in Rack (whenever it is, not intrested in when) or it will remain headless oriented?
Or is there an existing way to get a graphical interface going with this method and I'm just talking fried air (as we're used to say in Italy)?

Your work is actually inspiring, thank you.
Alessandro

**Comment by AndrewBelt** [comment]
Likely not. The purpose of HelloDAW is to get your build system up and running with the simplest possible example that proves that your built plugin works. Other API details are relatively easy after you can start digging in code rather than IDEs/builds, so that is beyond the scope of HelloDAW.
